### PR TITLE
Updated Clothing Shop - Less Goofy update

### PR DESCRIPTION
**Pull request by Heavybob**
images akamai steamusercontent
107410_screenshots_2016-01-15_00004
107410_screenshots_2016-01-15_00006
107410_screenshots_2016-01-15_00003

I understand the idea behind putting the player in the middle of nowhere in a black box void while buying clothing but honestly its really ominous. 

I would suggest to put some hooks to the master config to define if the black box should be enabled or disabled and also config on clothing shop pos.

### CODE REVIEW

**Comment by sargken** [comment]
Idea: Make multiple spawn points for the clothing shops depending on which shop it is.

**Comment by Heavybob** [comment]
Thats a really good idea.

**Comment by sargken** [comment]
You could do a switch per side and each case is diff faction, each faction has its own little clothing shop area.

**Comment by Heavybob** [comment]
I'll probs leave that one up to dan for that but I will get some positions pre-done.

**Comment by sargken** [comment]
If you get positions I can write it up if you want.

**Comment by Heavybob** [comment]
NP

// REB
[13590,12214.6,0.00141621];

// BRUCE
[17088.2,11313.6,0.00136757]

// COP
[12817.5,16722.9,0.00151062]

**Comment by danielstuart14** [comment]
what about at night?

**Comment by sargken** [comment]
Could turn the screen to NVG on?

**Comment by Heavybob** [comment]
Got a better solution, submitting a commit in a sec.

**Comment by Heavybob** [comment]
Just after _testLogic setPosATL _pos;

// Lighting
light = "#lightpoint" createVehicleLocal _pos;
light setlightbrightness 0.5;
light setlightcolor [1,1,1];
light setlightambient [1,1,1];

Then after player setDir _oldDir;
{deleteVehicle _x;} foreach [light];

Recheck the two submition requests then attach that code when you are ready Dan. 

images akamai steamusercontent

**Comment by sargken** [comment]
Nice. I will add light point into my nerge tomarrow.

**Comment by danielstuart14** [comment]
great, tomorrow I'll take a look.
I'm thinking in creating a random location. (Ex: it choose one of multiple pre-determinated locations, or, Ex: it choose a random location that is 100m far from any building.)

**Comment by sargken** [comment]
Only one of these requests will work otherwise we will have merge conflicts.

**Comment by Heavybob** [comment]
My changes aren't too drastic, would be awesome if you could just adapt my proposal into your commit sargken that would be awesome.

**Comment by sargken** [comment]
With the lighting? Yes that was my plan for tomorrow.

**Comment by Heavybob** [comment]
Right o.

**Comment by danielstuart14** [comment]
Will close, after thinking about it, I just realised that it will give a pain in the ass.
Imagine if admin set a building right on this place? Or if a chopper just fall there.

It must be spawned away from map. 
I added light to our current clothing system. And as I said before, I can't fix this clothing system as I don't have this issue.

**Comment by Heavybob** [comment]
Hey dan, think we could have a word outside of github? Pm steam details buddy.

**Pull request closed without merging**
