### PR TITLE
Fixes Issues with Screen Resolution

### PR DESCRIPTION
**Pull request by sargken**
The Pictures would overlap and not look good along with the text size would be too big so you couldn't read all of the text like 100 you would see 10 and half the last 0. Now both of these issues are fixed for all screen resolutions.

### CODE REVIEW

**Comment by sargken** [comment]
The only issue i found is on a larger resolution http://images.akamai.steamusercontent.com/ugc/365155533177636212/EF68E2D98666D58022891AEE10A083EA1B455D92/. The Images are small, we may be able to do some coefficent work with that to make they size back up for different resolutions.

**Comment by danielstuart14** [comment]
reverted. will take a look...
Can you attach a print with the previous bug?

**Comment by sargken** [comment]
Sorry i wasn't able to get on my pc to post what it was originally. I will sometime this week.

**Comment by sargken** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=592265178 

This is the pic with the bug that i was getting.

**Pull request merged**
